groups:
  # API 服务告警
  - name: attentionsync-api
    rules:
      - alert: APIHighErrorRate
        expr: rate(http_requests_total{job="attentionsync-api",status=~"5.."}[5m]) > 0.05
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "API error rate is high"
          description: "API error rate is {{ $value }} for more than 2 minutes"

      - alert: APIHighLatency
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="attentionsync-api"}[5m])) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "API latency is high"
          description: "95th percentile latency is {{ $value }}s"

      - alert: APIDown
        expr: up{job="attentionsync-api"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "API service is down"
          description: "AttentionSync API service is not responding"

  # 数据库告警
  - name: database
    rules:
      - alert: PostgreSQLDown
        expr: up{job="postgres"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "PostgreSQL is down"
          description: "PostgreSQL database is not responding"

      - alert: PostgreSQLHighConnections
        expr: pg_stat_database_numbackends / pg_settings_max_connections > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "PostgreSQL connection usage is high"
          description: "Connection usage is {{ $value | humanizePercentage }}"

      - alert: PostgreSQLSlowQueries
        expr: rate(pg_stat_database_tup_fetched[5m]) / rate(pg_stat_database_tup_returned[5m]) < 0.1
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "PostgreSQL has slow queries"
          description: "Query efficiency is low: {{ $value | humanizePercentage }}"

  # Redis 告警
  - name: redis
    rules:
      - alert: RedisDown
        expr: up{job="redis"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Redis is down"
          description: "Redis cache service is not responding"

      - alert: RedisHighMemoryUsage
        expr: redis_memory_used_bytes / redis_memory_max_bytes > 0.9
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Redis memory usage is high"
          description: "Memory usage is {{ $value | humanizePercentage }}"

      - alert: RedisHighConnectionCount
        expr: redis_connected_clients > 100
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Redis connection count is high"
          description: "Connected clients: {{ $value }}"

  # 系统资源告警
  - name: system
    rules:
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is {{ $value }}% on {{ $labels.instance }}"

      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 0.9
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is {{ $value | humanizePercentage }} on {{ $labels.instance }}"

      - alert: DiskSpaceRunningOut
        expr: (node_filesystem_avail_bytes / node_filesystem_size_bytes) < 0.1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Disk space is running out"
          description: "Available disk space is {{ $value | humanizePercentage }} on {{ $labels.instance }}"

  # 任务队列告警
  - name: celery
    rules:
      - alert: CeleryWorkerDown
        expr: celery_workers_active == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "No Celery workers active"
          description: "All Celery workers are down"

      - alert: CeleryQueueBacklog
        expr: celery_queue_length > 1000
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Celery queue has backlog"
          description: "Queue length is {{ $value }}"

      - alert: CeleryTaskFailureRate
        expr: rate(celery_task_failed_total[5m]) / rate(celery_task_total[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High Celery task failure rate"
          description: "Task failure rate is {{ $value | humanizePercentage }}"

  # 业务指标告警
  - name: business
    rules:
      - alert: LowUserActivity
        expr: rate(user_active_total[1h]) < 10
        for: 30m
        labels:
          severity: warning
        annotations:
          summary: "User activity is low"
          description: "Active users per hour: {{ $value }}"

      - alert: HighContentFetchFailureRate
        expr: rate(content_fetch_failed_total[10m]) / rate(content_fetch_total[10m]) > 0.2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High content fetch failure rate"
          description: "Failure rate is {{ $value | humanizePercentage }}"

      - alert: AIServiceDown
        expr: ai_service_available == 0
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "AI service is unavailable"
          description: "AI summarization service is not responding"